name: Install Common Deps for UniFFI Tasks
runs:
  using: composite
  steps:
    - name: Install cargo-make
      uses: taiki-e/install-action@5b4d68e2e660441203ab128a23676f1e4faf1532 # v2.86.3
      with: { tool: cargo-make@0.37 }
